# Screen draw constants
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FRAMERATE = 60

# Asteroid constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player constants
PLAYER_RADIUS = 20
PLAYER_SPRITE_COLOR = "white"
PLAYER_LINE_THICKNESS = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# Shot constants
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 5
SHOT_COLOR = "white"
